### ISSUE TITLE
Generalize plotting parameters

### ISSUE THREAD

**Issue by mafrahm** [uhh-cms/columnflow#105]
The number of plotting parameters is getting larger and larger. Handling some features with individual parameters is nice for some major styling features but doing this for all kinds small styling options seems tedious if not impossible.
However, with the `process_settings`, we already have a nice example for some kind of generalized plotting parameter, using the MultiCSVParamter and parsing to hand over a dictionary of dictionaries via command line (or the config).

We should continue with this approach to declare some general plotting parameters to minimize the number of required input parameters while also allowing full customization via task parameters in self-written plotting functions.

My proposal for such plotting parameters:
`process_settings` as already implemented for handling process-specific information
`general_settings` to summarize plotting parameters such as `yscale`, `skip_ratio`, `skip_cms` etc. into a a single parameter (but maybe still keep the current set of plotting parameters to allow overriding these settings)
`style_config` to override the defaults set in the `default_style_config` (e.g. [1])
`plot_cfg` to override the defaults set in the (soon to-be-called `default_plot_cfg`) (e.g. [2])
`variable_settings`, `selector_step_settings` etc.: not sure if really necessary, but we could also include settings analogous to `process_settings` for all kinds of task input parameters. I'd wait for an actual use case of such parameters before implementing them.

[1] https://github.com/uhh-cms/columnflow/blob/master/columnflow/plotting/example.py#L327
[2] https://github.com/uhh-cms/columnflow/blob/master/columnflow/plotting/example.py#L269

**Comment by riga** [comment]
@mafrahm Do you think this issue can be closed once #126 is merged?
