### ISSUE TITLE
Fast setup for newcomers

### ISSUE THREAD

**Issue by mafrahm** [uhh-cms/columnflow#106]
We should include some script that quickly sets up a new repository with some kind of default analysis such that newcomers can quickly start with their analysis and do not have to worry about things that are mostly analysis-independent.

This default analysis should include:
- a config setup that separates parts which are anaylsis-dependent (e.g. datasets, processes, defaults, variables, categories, ...) from parts that mostly stay the same for all analyses (e.g. setup required for jec/jer calibrations, most of the shifts, ...)
- a large set of default variables from which you can pick what you're interested in
- a small set of categories, selectors, producers (as already implemented, but we should maybe take some time to think about what the "perfect" default setup would look like (thinking from the standpoint of newcomers that have no idea of everything))
- (at some point) default producer for all relevant (analysis-independent) systematic uncertainties
- (at some point) default setup for a simple DNN
- (at some point) default inference model setup
- some documentation (as a shell script?) how to run some key tasks

We could also use this baseline analysis as a basis for CI tests (e.g. comparing values of a histogram after every new commit).

Feel free to add points that should be included in the default analysis

**Comment by andreypz** [comment]
Would also be good to have a bit of documentation: where (which file/method) certain functionality is implemented. So that new comers know what files to change for their.

**Comment by riga** [comment]
An analysis template was added by #142, which let's users create a minimal (for now somewhat cms-specific) analysis setup via

```shell
curl https://raw.githubusercontent.com/uhh-cms/columnflow/master/create_analysis.sh | bash
```

The documentation has to be adapted and continue which is tracked in #138 and #139.
