### ISSUE TITLE
enable direct input of numpy arrays

### ISSUE THREAD

**Issue by pkausw** [uhh-cms/columnflow#143]
It would be nice to support also `numpy` arrays (i.e. `npz`) files for processing.

**Comment by riga** [comment]
Can you maybe describe a potential workflow, i.e., where np arrays would be injected and what parts of cf should be used on top of those arrays, such as producers, etc.?

Since most core features are adapted to ak arrays in the structure they are provided by nano, calibrators, selectors and producers along the line, I'm not sure how to picture the np injection.

**Comment by pkausw** [comment]
I'm thinking of capabilites for projects derived from/building on cf itself. For example, I was specifically thinking of the mlforge project, where the goal is to train ML methods with cf as a back-end to profit from the workflow capabilities. It would be nice if we could use the parallization of the `ChunkedIOHandler` (sorry if I spelled that wrong) for e.g. tasks for pre-processing, where the original data could very well be in e.g. `npz` files. 

I think the implementation in cf should be fairly straight forward since `awkward` already supports initialization from numpy files (I think), and it also shouldn't complicate/break something else, right? Basically, we would just support another file format for the initial steps and then would enforce the parquet format as always (where appropriate of course).

**Comment by riga** [comment]
I think the answer consists of two parts.

- Projects using cf that want to use numpy arrays as input files can - of course - do that. However, they'd have to create a new task that reads numpy files as all [existing tasks](https://github.com/uhh-cms/columnflow/issues/25#issue-1258137827) are bound to use either root or parquet inputs in a specific structure. Also, they require meta data (such as a dataset or shift instance) passed via parameters (`--dataset`, `--shift`) and I'm not sure if one would want to change the current implementation, or mimic this meta data on the user side when running on numpy arrays.

- IO is another topic. The tasks require columnar input which would force you to work with recarrays. However, there is no method (at least I'm not aware of any) to load only a chunk of rows, so the `ChunkedIOHandler` would also not help users in this regard.

So apart from existing tasks and our custom IO tools, one could of course use all other features (conda env, sandboxes, base tasks, utils, columnar utils), but for the former two I don't really see a good use case.

**Comment by riga** [comment]
Closing for now, but we should reopen in case we need to dive deeper into this topic with future projects.
