### ISSUE TITLE
Machine learning for multiple configs

### ISSUE THREAD

**Issue by mafrahm** [uhh-cms/columnflow#208]
We should allow multiple configs as inputs for the MLTraining task, since it is quite common to train a single DNN for multiple years of data-taking.

**Comment by riga** [comment]
From a private discussion:

The `MLTraining` task should neither *have* a config, *nor* allow setting a selector / producer / etc on the command line. These decisions **must** only be subject to the MLModel object. The latter **is** already a parameter of the `MLTraining` so no everything remains configurable, the responsibility to do so is simply shifted from the task to the model.

This is not just cleaner, it's also generic and allows adding the proposed feature.

Side note: A possible future "BinOptInterface" would be almost identical regarding it's connection to the task structure.
