### ISSUE TITLE
Configure awkward_parquet to load specific nested columns

### ISSUE THREAD

**Issue by riga** [uhh-cms/columnflow#38]
There are a couple places where we would have the info to load only certain nested columns, but we do not yet pass this info to the awkward_parquet loader since we haven't found a way to passthrough this to parquet itself. To accelerate IO, we should find a way.

**Comment by riga** [comment]
https://github.com/uhh-cms/analysis_playground/blob/04273f7e28487e80294ef2f91c9fbefa30a5f8df/ap/tasks/production.py#L73-L78

**Comment by riga** [comment]
https://github.com/uhh-cms/analysis_playground/blob/04273f7e28487e80294ef2f91c9fbefa30a5f8df/ap/tasks/histograms.py#L72-L77

**Comment by pkausw** [comment]
After some quick tests, I think it's best to go away from the `ak.from_parquet` function and open the parquet files with `parquet` directly. We can then create a `pyarrow.Table` object with the `ParquetFile.reat()` function, where we can specify the columns. The format of the string for nested columns is not straight forward but can be implemented into the `Route` objects. For example, the format to load `Jet.pt` would be `Jet.list.item.pt`.

Finally, we can obtain the awkward array with `ak.from_arrow`, where we give it the `pyarrow.Table` object.

I have created a branch for this feature: `features/load_specifc_column_from_parquet`

**Comment by riga** [comment]
There has been an update of the [`from_parquet` interface](https://awkward-array.readthedocs.io/en/latest/_auto/ak.from_parquet.html) in awkward since v1.10.1 which can help implementing the feature mentioned in this issue.

**Comment by riga** [comment]
The columns to load are fully configured now in various places, such as SelectEvents, ReduceEvents, ProduceColumns, PrepareMLEvents, MLEvaluation, and CreateHistograms, so the actual work is done. However, there is bug (I think) in the upstream dask_awkward package, that is documented in #117.

We can close *this* one.
